---
title: "Sol"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(babynames)

name_data <- 
  babynames %>% 
  filter(name == "Sol") %>% 
  mutate(sex = case_when(sex == "M" ~ "Male", 
                         sex == "F" ~ "Female"))

# Número total de niños
n <- sum(name_data$n)

# most$year es el año más popular
# most$n es el número de niños nacidos ese año
# most_sex indica si esos niños fueron niños o niñas
most <- name_data %>% 
  filter(n == max(n))

most_sex <- most %>% 
  pull("sex") %>% 
  switch("Male" = "niños", "Female" = "niñas")

# Has the name been a boy's or girl's name?
sex <-
  name_data %>% 
  group_by(sex) %>% 
  summarise(n = sum(n)) %>% 
  filter(n == max(n)) %>% 
  pull("sex") %>% 
  switch("Male" = "ninho", "Female" = "ninha")
```

Ha habido en total `r n` niños llamados Sol. El nombre Sol fue más popular en `r most$year`, cuando `r most$n` `r most_sex` se llamaron Sol. Sol es tradicionalmente un nombre de `r sex`.

```{r echo=FALSE}
name_data %>% 
  ggplot() +
    geom_ribbon(mapping = aes(x = year, ymax = prop, fill = sex), ymin = 0, alpha = 0.5) +
    labs(title = "Popularidad del nombre Sol", 
         subtitle = "Proporcion de ninhos y ninhas llamados Sol, 1880-2017", 
         caption = "Datos de la US Social Security Administration",
         y = "proportion") +
    theme_bw()
```


