---
title: "`r params$name`"
params: 
  name: "Garrett"
---

```{r setup, include=FALSE}
library(tidyverse)
library(babynames)
library(glue)

name_data <- 
  babynames %>% 
  filter(name == params$name) %>% 
  mutate(sex = case_when(sex == "M" ~ "Male", 
                         sex == "F" ~ "Female"))

n <- sum(name_data$n)

most <- name_data %>% 
  filter(n == max(n))

most_sex <- most %>% 
  pull("sex") %>% 
  switch("Male" = "niños", "Female" = "niñas")

sex <-
  name_data %>% 
  group_by(sex) %>% 
  summarise(n = sum(n)) %>% 
  filter(n == max(n)) %>% 
  pull("sex") %>% 
  switch("Male" = "niño", "Female" = "niña")
```

Ha habido en total **`r n`** niños llamados `r params$name`. El nombre `r params$name` fue más popular en `r most$year`, cuando hubo `r most$n` `r most_sex` llamados `r params$name`. `r params$name` es tradicionalmente un nombre de `r sex`.

```{r echo = FALSE}
name_data %>% 
  ggplot() +
    geom_ribbon(mapping = aes(x = year, ymax = prop, fill = sex), ymin = 0, alpha = 0.5) +
    labs(title = glue("Popularidad del nombre {params$name}"), 
         subtitle = glue("Proporción de niños y niñas llamados {params$name}, 1880-2017"), 
         caption = "Datos de la US Social Security Administration",
         y = "proportion") +
    theme_bw()
```


